# Site settings
title: Learning to Live and Code
header-img: img/home-bg.png
email: nicoletherien@yahoo.com
copyright_name: nicoletherien
description: > # this means to ignore newlines until "baseurl:"
  Finding happiness in life and learning to code along the way
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nicoletherien
learn_profile: nicoletherien
email_username: nicoletherien@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
